name: Release CLI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  # Specify the Go version you want to use

    - name: Build CLI
      run: |
        go build -o birdcli ./...

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}  # Use the tag that triggered the action
        files: ./birdcli  # Specify the built binary file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      if: steps.create_release.outputs.id  # Moved if condition to a separate line
      run: |
        echo "Release created with ID: ${{ steps.create_release.outputs.id }}"
