name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on new version tags (e.g., v1.0.0)

jobs:
  build-mac:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'  # Replace with your Go version

      # Cache Go modules for faster builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install GoReleaser
      - name: Install GoReleaser
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/download/v2.4.5/goreleaser_Linux_x86_64.tar.gz | tar -xz
          sudo mv goreleaser /usr/local/bin/

      # Run GoReleaser to build and release
      - name: Run GoReleaser
        run: |
          goreleaser release --config .goreleaser/mac.yml --clean
