name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on new version tags (e.g., v1.0.0)

jobs:
  build-mac:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
          clean: true     # Ensure a clean working directory

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'  # Replace with your Go version

      # Cache Go modules for faster builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Clean working directory (if needed)
      - name: Clean working directory
        run: git restore . && git clean -fd

      # Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v2.4.5
          args: release -f .goreleaser/mac.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}